# Generated by Django 4.1.5 on 2023-01-29 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('month_salary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hour_salary', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience', models.FloatField()),
                ('is_ready_to_relocate_city', models.BooleanField(blank=True, null=True)),
                ('is_ready_to_relocate_country', models.BooleanField(blank=True, null=True)),
                ('skills', models.TextField()),
                ('english_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('employment_rate', models.CharField(blank=True, choices=[('OFF', 'Office'), ('REM', 'Remote'), ('O\\R', 'Office\\Remote')], max_length=3, null=True)),
                ('about_work_experience', models.TextField(blank=True, null=True)),
                ('about_work_expectations', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('skype', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=17, unique=True)),
                ('telegram', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
                ('portfolio_url', models.URLField()),
                ('cv_file', models.FileField(upload_to='cv_files/')),
                ('avatar_img', models.ImageField(upload_to='avatar_files/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_profile.managers.UserProfileManager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.worktype')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.country'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fav_contact_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.contactmethod'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.workcategory'),
        ),
    ]
