# Generated by Django 4.1.5 on 2023-01-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_remove_candidate_email_alter_candidate_avatar_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employ_count',
            field=models.CharField(choices=[('1-10', '1-10'), ('10-100', '10-100'), ('100-250', '100-250'), ('500+', '500+')], max_length=7),
        ),
    ]
