# Generated by Django 4.1.5 on 2023-01-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_employer_employ_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='is_ready_to_relocate_city',
        ),
    ]
