# Generated by Django 4.1.5 on 2023-02-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_remove_candidate_is_ready_to_relocate_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_active_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
