# Generated by Django 4.1.5 on 2023-02-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_candidate_is_active_profile_candidate_work_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
