# Generated by Django 4.1.5 on 2023-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_alter_candidate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='Noneuser_upload/avatar_files/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='Noneuser_upload/cv_files/'),
        ),
    ]
