# Generated by Django 4.1.5 on 2023-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_candidate_avatar_img_alter_candidate_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_upload/avatar_files/'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='static/user_upload/cv_files/'),
        ),
    ]
