# Generated by Django 4.1.5 on 2023-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_candidate_avatar_img_alter_candidate_cv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/user_upload/avatar_files/'),
        ),
    ]
